version: 2

sources:
  - name: olist_raw
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: olist_raw
    tables:
      - name: olist_customers_dataset_view
      - name: olist_orders_dataset_view
      - name: olist_order_items_dataset_view
      - name: olist_order_payments_dataset_view
      - name: olist_order_reviews_dataset_view
      - name: olist_products_dataset_view
      - name: olist_sellers_dataset_view
      - name: olist_geolocation_dataset_view
      - name: product_category_name_translation_view
